initial version

diff --git a/vcompress_gui b/vcompress_gui
--- a/vcompress_gui
+++ b/vcompress_gui
@@ -1,23 +1,24 @@
 #!/bin/bash
 
-if [[ $# -eq 0 ]] ; then
-    echo "No specified file."
-    exit 1
-fi
-
+# exit on error
 set -e
 
-ls -lh $1
+kdialog --passivepopup "Converting "$1 1
 
-echo "ffpb -hwaccel cuda -i "$1" -c:v hevc_nvenc -c:a libopus -crf 26 "$1".opt.mp4"
-eval "ffpb -hwaccel cuda -i "$1" -c:v hevc_nvenc -c:a libopus -crf 26 "$1".opt.mp4"
+# original size
+size_o=`du -h $1 | cut -f1`
+# transcode with ffmpeg
+eval "ffmpeg -hwaccel cuda -i "$1" -c:v hevc_nvenc -c:a libopus -crf 26 "$1".opt.mp4"
+# size after transcoding
+size_a=`du -h $1.opt.mp4 | cut -f1`
 
-ls -lh $1".opt.mp4"
 
-read -p "Are you sure? " -n 1 -r
-echo
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
-    trash $1
-    mv $1".opt.mp4" $1
+kdialog --yesno $size_o" => "$size_a"\nAre you sure?"
+if [[ $? -ne 0 ]] ; then
+    exit 0
 fi
+
+# replace
+trash $1
+mv $1".opt.mp4" $1
+kdialog --passivepopup "Done" 1
